name: Documentation

on:
  push:
    branches: [ dev/documentation ]

jobs:
  make-doc:
    name: Generate the documentaion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install doxygen
        run: sudo apt install doxygen
      - name: Run doxygen
        run: doxygen ./Doxyfile
      - name: Commit master
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add doc/ -f
          git commit -m "generate documentation"
      - name: Push master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
      - name: Copy on documentation
        run: |
          git checkout master
          git checkout documentation -- doc
      - name: Commit documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add doc/ -f
          git commit -m "generate documentation"
      - name: Push documentation
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master