name: Documentation

on:
  push:
    branches: [ dev/documentation ]

jobs:
  make-doc:
    name: Generate the documentaion
    runs-on: ubuntu-latest
    step:
      - name: Checkout code
        uses: actions/checkout@dev/documentation
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Run make doc
        run: make doc
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add doc/ -f
          git commit -m "generate documentation"
      - name: Push
        uses: ad-m/github-push-action@dev/documentation
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
