name: Documentation

on:
  push:
    branches: [ dev/documentation ]

jobs:
  make-doc:
    name: Generate the documentaion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install doxygen
        run: sudo apt install doxygen
      - name: Run doxygen
        run: doxygen ./Doxyfile
      - name: Remove uncessessary files
        run: |
          rm -rf build
          rm -rf cmake
          rm -rf data
          rm -rf include
          rm -rf qt
          rm -rf src
          rm -rf .clang-format
          rm -rf CMakeLists.txt
          rm -rf Doxyfile
          rm -rf Makefile
      - name: Commit documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add doc/ -f
          git commit -m "generate documentation"
      - name: Push documentation
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: documentation
          force: true
