name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  make-doc:
    name: Generate the documentaion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install doxygen
        run: sudo apt install doxygen
      - name: Update documents version
        run: |
          sed -i "s/# AtilaCalculatorSoftware v[ 0-9\.]*/# AtilaCalculatorSoftware v$(cat "include/version.h" |grep "#define" |grep "VERSION_MAJOR" |cut -d ' ' -f3).$(cat "include/version.h" |grep "#define" |grep "VERSION_MINOR" |cut -d ' ' -f3).$(cat "include/version.h" |grep "#define" |grep "VERSION_PATCH" |cut -d ' ' -f3)/" README.md
          sed -i "s/PROJECT_NUMBER[ ]*=[ 0-9\.]*/PROJECT_NUMBER         = $(cat "include/version.h" |grep "#define" |grep "VERSION_MAJOR" |cut -d ' ' -f3).$(cat "include/version.h" |grep "#define" |grep "VERSION_MINOR" |cut -d ' ' -f3).$(cat "include/version.h" |grep "#define" |grep "VERSION_PATCH" |cut -d ' ' -f3)/" Doxyfile
      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add . -f
          git commit -m "update version"
      - name: Push version update on master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
      - name: Run doxygen
        run: doxygen ./Doxyfile
      - name: Remove uncessessary files
        run: |
          rm -rf build
          rm -rf cmake
          rm -rf data
          rm -rf include
          rm -rf qt
          rm -rf src
          rm -rf .clang-format
          rm -rf CMakeLists.txt
          rm -rf Doxyfile
          rm -rf Makefile
      - name: Commit documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add . -f
          git add doc/ -f
          git commit -m "generate documentation"
      - name: Push doc on documentation
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: documentation
          force: true
